version: 2

sources:
  - name: raw
    database: LOAD
    schema: WEB_SCHEMA

    tables:
      - name: sessions
      - name: orders
      - name: item_views
      - name: expenses
      - name: returns
      - name: hr_joins
      - name: hr_quits
