SELECT
    _fivetran_id,
    SESSION_ID,
    ITEM_NAME,
    ITEM_VIEW_AT AS ITEM_VIEW_TIME,
    PRICE_PER_UNIT,
    ADD_TO_CART_QUANTITY,
    REMOVE_FROM_CART_QUANTITY,
    _FIVETRAN_DELETED,
    _FIVETRAN_SYNCED
FROM {{ source('web', 'item_views') }}