version: 2

sources:
  - name: google_drive
    database: LOAD
    schema: GOOGLE_DRIVE
    tables:
      - name: expenses
        config:
          freshness:
            warn_after: {count: 1, period: day}
            error_after: {count: 2, period: day}
         

      - name: returns
        config:
          freshness:
            warn_after: {count: 1, period: day}
            error_after: {count: 2, period: day}
       

      - name: hr_joins
        config:
          freshness:
            warn_after: {count: 1, period: day}
            error_after: {count: 2, period: day}
        

      - name: hr_quits
        config:
          freshness:
            warn_after: {count: 1, period: day}
            error_after: {count: 2, period: day}
    

  - name: web
    database: LOAD
    schema: WEB_SCHEMA
    tables:
      - name: sessions
        config:
          freshness:
            warn_after: {count: 1, period: day}
            error_after: {count: 2, period: day}
        

      - name: page_views
        config:
          freshness:
            warn_after: {count: 1, period: day}
            error_after: {count: 2, period: day}
       

      - name: item_views
        config:
          freshness:
            warn_after: {count: 1, period: day}
            error_after: {count: 2, period: day}
     

      - name: orders
        config:
          freshness:
            warn_after: {count: 1, period: day}
            error_after: {count: 2, period: day}
  